spring.application.name=citizens-registry-client
server.port=8081
# Disable banner for cleaner console
spring.main.banner-mode=off
# Disable web server (CLI app)
spring.main.web-application-type=none
